### PR TITLE
API refactorings

### PR DESCRIPTION
**Pull request by juliangruber**

### CODE REVIEW

**Comment by Dieterbe** [comment]
"windows, wtf" doesn't say which problem it solves.
and what's the benefit of the changed api?

**Comment by juliangruber** [comment]
sorry, I was a bit hectic with those changes. I removed the operation system restriction. And the changed api is for brevity, no need to assign StatsD to exports.StatsD when that's the only object to be exported.

**Comment by Dieterbe** [comment]
_why_ did you remove the operating system restriction? what problem does this solve? does it run on windows? did you test it? why do we have to guess all this? how about solaris or other bsd's?

**Comment by juliangruber** [comment]
it runs on windows. there is no reason it wouldn't run on any platform node officially supports.

**Comment by Dieterbe** [comment]
the api changes look allright, though your commit 'refactorings' and 'Update README.md' should get squashed together as they pertain to the same logical change, and be given a more descriptive commit message.  the 'windows, wtf' commit should def. get a more descriptive commit message. one that has all the info you explained to me here.

**Comment by Dieterbe** [comment]
feel free to open a new PR with the fixes.

**Pull request closed without merging**
