### PR TITLE
Adding function for closing socket 

### PR DESCRIPTION
**Pull request by goelvivek**
Signed-off-by: GoelVivek goelvivek2011@gmail.com

### CODE REVIEW

**Comment by devdazed** [comment]
Can you provide the use case/need for this.  The socket is never bound to receive messages.

**Comment by goelvivek** [comment]
Only use case is node will fail to exit, after using any statsd call. As
statsd socket is still open.

regards
Vivek Goel

**Comment by devdazed** [comment]
Good catch, lets write a test for it and I will merge it in.  Thanks.

**Comment by goelvivek** [comment]
Sorry, I thought but not able to come to conclusion , what test case to
write for socket close.
Do you want me to call socket.close and after check is it really closed or
not ?

regards
Vivek Goel

**Comment by devdazed** [comment]
That should be sufficient.  I just want to ensure as much code is tested as possible.

**Comment by dportabella** [comment]
I have an issue, which I think it is the same as goelvivek:
I have the following simple test.js script:

```
var StatsD = require('node-statsd').StatsD;
var statsDClient = new StatsD();
statsDClient.gauge("my_gauge", "15");
```

running the script "node test.js" I would expect that the script sends the gauche, and then it exists;
but that's not the case, the script is hold on forever.
is there an easy way to solve this issue?

**Comment by devdazed** [comment]
`statsDClient.socket.close()` should work for now, at least until we get this pulled in.

**Comment by goelvivek** [comment]
Socket.close is creating problem, if it is immediately fired after statsd call. May be , We need to wait for all data to be submitted before calling socket.close.

**Comment by devdazed** [comment]
hmm, maybe if we have an internal counter that gets incremented every time we send a packet and decremented every time a callback is received after send. Then in the `statsd.close()` method, we can wait until that counter is 0 before closing the underlying socket.  how does that sound?

**Comment by goelvivek** [comment]
Good. I think that approach will work.

**Comment by OrangeDog** [comment]
I get the following on Node 0.8.22 when trying to shutdown my server.

```
Error: Not running
    at Socket._healthCheck (dgram.js:311:11)
    at Socket.close (dgram.js:218:8)
```

Edit: Need to check whether socket.fd is set before trying to close it.

**Comment by devoncrouse** [comment]
+1 to not having to write an awkward async thing to wait for each metric callback before closing the socket manually. This is getting stale...

**Comment by sivy** [comment]
Updates, anyone?

**Pull request merged**
