### PR TITLE
Fix some global leaks and satisfy jshint.

### PR DESCRIPTION
**Pull request by booo**
What do you think of this?

Best Regards
Philipp

### CODE REVIEW

**Comment by Dieterbe** [comment]
i think this looks allright, i'll need to test run this..

**Comment by booo** [comment]
Do you need any help to test run this? Would be nice if we could get this into the master branch and update the npm package as well.

**Comment by Dieterbe** [comment]
yeah i'm currently busy with another project. are you running this successfully in production?

**Comment by booo** [comment]
Not a the moment... I don't think there are any changes that could break functionality.

**Comment by Dieterbe** [comment]
well, as soon as somebody can confirm it works fine in production (whether that's me or you) i'll merge it in.

**Comment by devdazed** [comment]
This is taken care of in the latest set of changes.

**Comment by booo** [comment]
Thanks a lot!

Maybe you should consider adding jshint to the dev scripts?!

**Comment by devdazed** [comment]
i use jshint in my development environment, however I'm not sure what you mean by adding it to the dev scripts.  If you can provide me with an example id be happy to take a look.

**Comment by booo** [comment]
Add jshint to the devDependencies. Add it to the test target of the package.json. The result would be that we hint the code on every commit. Maybe you want to add a .jshintrc file and wait for the 1.0.0 version of jshint to be published on npm.

**Pull request closed without merging**
